### ISSUE TITLE
Comments available only anonymous user?

### ISSUE THREAD

**Issue by typo3ua** [nitsan-technologies/ns_news_comments#1]
Does exist configuration for logged users (fe_user)..., Does comments available only anonymous user?

**Comment by nitsan-technologies** [comment]
Hey @typo3ua 

**Comment by Anonymous**
Right, currently only the anonymous user able to write comments.

**Comment by fe_user**
Sounds good idea! Sure, we will provide such feature like logged-in fe_user can give a comment, so comment's fields like name/email will automatically come from user's account. We are accepting your this "Feature" and will implement in next release :)

Cheers,
Sanjay

**Comment by jooler** [comment]
It's very useful.

**Comment by nitsan-technologies** [comment]
Hey @typo3ua  & @jooler 

Thank you for your suggestion.

We just have uploaded extension with FE_User functionality at git repository.
Still, It is in Testing. But you can download this from this repository. And share your valuable feedback with us.
URL:  https://github.com/nitsan-technologies/ns_news_comments/

Thank you :)
