### ISSUE TITLE
Permission issue for editor user

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_news_comments#11]
Hi,

First i have to thank you for the nice [NITSAN] Comment Plugin for 
EXT:news extension. It is very well designed and really useful in my 
actual project!

Im writing you, because i have a problem with the comment extension. 
Maybe you have a solution.

I have a typo3 9.5 installation with news and [NITSAN] Comment Plugin 
for EXT:news. If a comment is on a newsrecord, the editors cant open the 
newsrecord in the backend. I made a screenshot of the error message in 
the backend.

I tried to solve the problem by myself. But i have my skills more in the 
frontend development. Now i am searching for somebody who can fix this 
for me.

Can you fix the problem and how much money you would use for that?

I looking forward to your answer :)

Kind regards from Winterthur
Luki

![1](https://user-images.githubusercontent.com/2622317/53162380-ea8cd780-35f1-11e9-9458-26324451532b.png)
![2](https://user-images.githubusercontent.com/2622317/53162382-eb256e00-35f1-11e9-9b31-9aa030e574aa.png)

**Comment by daniele-c** [comment]
Hi! 
I had the same problem (see https://github.com/nitsan-technologies/ns_news_comments/issues/9). 
I fixed it and sent a pull request (see https://github.com/daniele-c/ns_news_comments/commit/632d205f8635bded35120d432b9b626734c440b5). 

Then you can define a storagePid for the comment-records.

**Comment by nitsan-technologies** [comment]
Hey, @daniele-c Thank you for your contribution :)

Hey Winterthur

Yes, Issue was generated because default all comments are stored in the page where you have used the plugin. 

We have resolved your issue and uploaded the latest code at GIT repository.
URL: https://github.com/nitsan-technologies/ns_news_comments/

To apply it you need to apply the following procedure.
1) First, you need to delete all comments which already exist in the table. (https://prnt.sc/mo6019)
2) Set storage at the plugin. You should set that storage page where all the news is stored. (https://prnt.sc/mo66mj)

Now, All the comments will store at the storage page which you have set in the plugin.

Have a great day ahead

Cheers!
