### ISSUE TITLE
Show comments on every page

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_news_comments#12]
Hi,

I‘m gladly using the News Comment Extension you provide for TYPO3. It’s the best I could find for now! But is there a possibility to show the comments on every page, regardless oft he pid? I may have multiple pages with the same news and want the comments to be shown on every one of them „globally“.  I would very much appreciate your help.

Kind regards,
Fabian Paz

**Comment by nitsan-technologies** [comment]
Hey, Fabian Paz

First of all, Thank you very much for your appreciations. We glad that you find the extension very useful.

We have already resolved this issue but unfortunately, the latest extension is still not uploaded on the TER. So, you may download the new latest version from **GIT Repository:** https://github.com/nitsan-technologies/ns_news_comments/

Please follow the below mentioned steps.

    **Step-1.** Download the extension (from GIT Repository) and set up in your environment.

    **Step-2.** Clear the cache from the TYPO3 Back-End.

    **Step-3.** You may now find the **Record Storage Page** option should be available, See this screenshot - https://prnt.sc/mxavju

    **Step-4.** Now, You should set a common **Record Storage Page** at all the pages where you have used this plugin. It should render all the comments of that particular NEWS globally at all the pages from storage page.

Please follow the above steps. Feel free to contact us again if you still have any doubts/problems.

**Note:** We will upload the latest version in the TER very soon ;)
You are always welcome for the new ideas and suggestions :)

Regards.

**Comment by Sidrartha** [comment]
Thanks a lot, works perfectly now!

**Comment by nitsan-technologies** [comment]
Perfect, Thanks for your confirmation. Feel free to connect with us for any further help/support.

Cheers,
Team NITSAN
