### ISSUE TITLE
Name filed doesnt accept unicode

### ISSUE THREAD

**Issue by ahmadkhoei** [nitsan-technologies/ns_news_comments#14]
Hello, 
The Name filed validation doesn't accept any UTF8 charachter. User can't enter names in Persian/Arabic/German or other languages.

**Comment by nitsan-technologies** [comment]
Hey @ahmadkhoei 

Thanks for reporting it.

We have resolved it in the new version of this extension.
You can download it from this GIT version.
**URL:** https://github.com/nitsan-technologies/ns_news_comments/

Soon we will upload at TER too with the new version of this extension.

Thanks!
