### ISSUE TITLE
Please add this extension to Typo3 translation server

### ISSUE THREAD

**Issue by ahmadkhoei** [nitsan-technologies/ns_news_comments#15]
Hello,
Please add this extension to typo3 translation server (translation.typo3.org).
The extension owner should request set-up in : https://forge.typo3.org/projects/team-translation

Thanks

**Comment by nitsan-technologies** [comment]
Hey,

Thanks for your suggestion. According to your request, we have raised a ticket at https://forge.typo3.org/issues/88430

Feel free to connect with us for any further support, Thank you!

Cheers,
Sanjay

**Comment by xperseguers** [comment]
Extension is available for translation: https://translation.typo3.org/projects/TYPO3.ext.ns_news_comments/
