### ISSUE TITLE
sendMailtoAdmin not working

### ISSUE THREAD

**Issue by medarob** [nitsan-technologies/ns_news_comments#22]
Hi,

I think we discovered a bug in the sentMailToAdmin E-Mail routine:

We have the standard settings:
```
settings.notification.siteadmin.sendMailToAdmin = 0
settings.notification.siteadmin.adminEmail = test@mail.com
```

but the system wants to send an email to "sek.test@mail.com". Why? We don't know... This leads to an 10sec delay everytime a users posts a comment.

We changed `adminEmail` to an existing mail and now it works. `sendMailToAdmin` is still 0.

(`isset` might be wrong here, it's `true` everytime?)

**Comment by nitsan-technologies** [comment]
Hey @medarob 

Thanks for your feedback.

Yes, That was an issue.
We have fixed it. And uploaded at TER with version 2.5.2

Still, if you get any suggestion or any issue you can register here.

Thanks!
