### ISSUE TITLE
The action "create" (controller "Comment") is not allowed by this plugin.

### ISSUE THREAD

**Issue by ekarakas** [nitsan-technologies/ns_news_comments#23]
My System:
Typo3 9.5.9
News Version: 7.2.3
ns_news_comments: 2.6

After installing and configuration i became an alert with internal Server error
In T3 Log i saw following Error:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1313855175: The action "create" (controller "Comment") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php. | TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException thrown in file /home/v9dev/htdocs/typo3_src-9.5.9/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php in line 275. Requested URL: https://v9dev.concardis.com/insights/artikel/apple-pay-ist-da?tx_nsnewscomments_newscomment%%5Baction%%5D=create&tx_nsnewscomments_newscomment%%5Bcontroller%%5D=Comment&tx_nsnewscomments_newscomment%%5BStoragepid%%5D=51&cHash=6679851ffd90408cf2d05e8c9b5ab1d2

If i disable the constant: Set Approval by admin
Than i becam the alert: parsererror SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

But the Comment ist saved!

**Comment by spiderrider** [comment]
You are not alone. I have exactly the same problem.

**Comment by nitsan-technologies** [comment]
Hello @here

Thanks to using this extension.
We will have a look at it. And will come with a new bugfree version of this extension.

@spiderrider regarding captcha.
Have you followed step 3? (https://i.imgur.com/ahnGFjd.png)
You can prefer this link https://www.nitsan.in/blog/post/t3ext-day-typo3-comment-plugin-for-ext-news/

Cheers!

**Comment by spiderrider** [comment]
Thank you for your answer.
Regarding captcha: I followed all steps. The captcha looks like a broken link. The enter field and the advice "Enter the above code here" is there, but no grafic.

**Comment by yeezy69** [comment]
I use the free version 4.2.1 of ns_news_comments.

Posting comment works (my setting: approveComment=1).

But while posting an exception in typo3 log appears: 

`TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException: The action "create" (controller "Nitsan\NsNewsComments\Controller\CommentController") is not allowed by this plugin / module.`

I found my problem: In file typo3conf/ext/ns_news_comments/Configuration/TypoScript/setup.txt the switchableControllerActions will set to approveComment only.

Adding 'create' to switchableControllerActions is the fix for me (or remove all the lines):

```
[{$plugin.tx_nsnewscomments.settings.approveComment} == "1"]
  page.315125 >
  page.315125 = USER
  page.315125{
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    pluginName = Newscomment
    extensionName = NsNewsComments
    controller = Comment
    vendorName = Nitsan
    action = show
    switchableControllerActions{
      Comment{
        1 = approveComment
        2 = create   # FIX
      }
    }
  }
[global]
```

**Comment by fzuerker** [comment]
This still seems to be an issue.
I have installed the free version 4.3.0 and got the same exception:
`"TYPO3\\CMS\\Extbase\\Mvc\\Exception\\InvalidActionNameException: The action \"create\" (controller \"Comment\") is not allowed by this plugin / module.`

When I add the create action to the switchableControllerActions like @yeezy69 did, commenting works, but every comment is created twice.

**Comment by yeezy69** [comment]
yes, comments created twice for me too. i disabled the whole block with /* */ 

```
/*
[{$plugin.tx_nsnewscomments.settings.approveComment} == "1"]
  page.315125 >
  page.315125 = USER
  page.315125{
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    pluginName = Newscomment
    extensionName = NsNewsComments
    controller = Comment
    vendorName = Nitsan
    action = show
    switchableControllerActions{
      Comment{
        1 = approveComment
        2 = create   # FIX
      }
    }
  }
[global]
*/
```

**Comment by nitsan-technologies** [comment]
Hello Everyone,

Unfortunately, this feature was intended for the premium version but missed removing code from here. We confirmed above solution works fine for free-version too. Once again sorry to everyone for such inconvenience caused to you :(
