### ISSUE TITLE
ns_news_comments 4.0.0 - how to check for new comments? 

### ISSUE THREAD

**Issue by 666Her0** [nitsan-technologies/ns_news_comments#27]
First of all - thank you for this great comment extension, you did a very good job of implementing comments in TYPO3 9.0.

We're having one issue tho - you stated that there is a possibility that an admin can get notified when a new comment is waiting for approval. 
We checked the code and saw that it looked kinda unfinished ( maybe we're looking in the wrong place). 

Is it possible that you're still working on a notification feature? If yes, do you know how long it'll take to be released? 

Best regards, 

Kevin

**Comment by nitsan-technologies** [comment]
Hey @666Her0 

- Thanks for your feedback.
- To your question, Unfortunately, such features are available in PRO version.
- Our management decided to make two variance (FREE and PRO) to keep support, maintain and extend features of the extension.
- I suggest you to support this project by considering to buy https://t3terminal.com/ns-news-comments-pro
- Sorry for this inconvenient, Of course, For your existing old-installation you can keep using FREE (without a license).

Cheers!
