### ISSUE TITLE
can't update from v4.1 to v4.2 via composer

### ISSUE THREAD

**Issue by medarob** [nitsan-technologies/ns_news_comments#31]
I tried to update the extension from 4.1 to 4.2 via composer but this didn't work.

```
bash-4.2$ composer update nitsan/ns-news-comments
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Generating class alias map file
Setting up TYPO3 environment and extensions.
24 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
I also tried to "require" the new version but this also failed:

```
bash-4.2$ composer req nitsan/ns-news-comments
Using version ^4.1 for nitsan/ns-news-comments
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
Generating class alias map file
Setting up TYPO3 environment and extensions.
24 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

On packagist there is no 4.2 tag available, maybe that's the reason why it didn't work?

![grafik](https://user-images.githubusercontent.com/33951787/86602135-867a7180-bfa2-11ea-80f7-bf2622b2546e.png)

**Comment by nitsan-technologies** [comment]
Dear @medarob 

We appreciate your feedback. Indeed, there was some issues between Github and Packagist. We have corrected issues, and have the latest release at Packagist too https://packagist.org/packages/nitsan/ns-news-comments Please try again, Hope it will work well for you.

Sorry for such inconvenience caused to you, Thank you!

Cheers,
Sanjay

**Comment by medarob** [comment]
Hi Sanjay, now it works. Thank you for the quick update :)
