### ISSUE TITLE
feuser not recognized

### ISSUE THREAD

**Issue by medarob** [nitsan-technologies/ns_news_comments#32]
Hi,

we use the news_comment extension in an intranet environment where every user is automatically recognized via ldap in the frontend.
Advantage: fields for name and email are automatically prefilled with the current username and email in the comment form.

Now I noticed that those fields are not prefilled anymore. `{name}` is not available (EMPTY) in the template like here

```
        <f:if condition="{name}">
            <f:then>
                <f:form.textfield property="username" id="name" placeholder="{f:translate(key:'name')}" class="validatethis" value="{name}" disabled="disabled"/>
            </f:then>
            <f:else>
                <f:form.textfield property="username" id="name" placeholder="{f:translate(key:'name')}" class="validatethis"/>
            </f:else>
        </f:if>
```

If I debug {_all} I get these values:
![grafik](https://user-images.githubusercontent.com/33951787/86920698-71304f00-c12a-11ea-989d-cab0bc212f23.png)

Is it correct that `userSettings` has the value `anonymoususer`?

I also noticed that I don't have the main config options anymore:

![grafik](https://user-images.githubusercontent.com/33951787/86921113-e865e300-c12a-11ea-9a07-f87cc354f326.png)

and only have 10 configurations and not 24 like in the documentation: https://docs.t3terminal.com/en/latest/ExtNsNewsComments/GlobalConfiguration/Index.html

![grafik](https://user-images.githubusercontent.com/33951787/86921446-74780a80-c12b-11ea-9484-aea1bce960a8.png)

We updated from v2.6 to 4.1 and now 4.2. Could that be an issue?

**Comment by nitsan-technologies** [comment]
Hi @medarob 

Thanks for your feedback.

Can you please visite - https://t3terminal.com/news-comment-typo3-extension Key features list section in free vs pro tab? - https://i.imgur.com/cO6X7RH.png

All 24 constants are available in pro version.

Thank you!
