### ISSUE TITLE
Comments not listed on translated articles

### ISSUE THREAD

**Issue by swisschocolate-zz** [nitsan-technologies/ns_news_comments#33]
If articles are translated, comments don't show up on the translations. Every comment should be listed on all translations, regardless on which translation of the article it was written. To achieve this, comments should always be stored with sys_language_uid = -1

If it is really desired to write and show comments depending on the current language, then (and only then) the sys_language_uid should be the id of the current languate, but the article id has to be that of the translated article.

**Comment by nitsan-technologies** [comment]
Hi @swisschocolate 

Thank you for your update and feedback.

We will think about this, and meanwhile, for your concern, you can achieve this kind of functionality with the site configuration and language fallbak. like this - https://i.imgur.com/lPwKPjn.png

You can try and share your feedback on the same.

Thank you!
