### ISSUE TITLE
Missing configuration in Constants and Setup

### ISSUE THREAD

**Issue by herzogkienast** [nitsan-technologies/ns_news_comments#39]
Hi there,
IMHO there are missing some configuration things in constants. The whole admin and mail stuff is missing in constants, also constant editor. Using TYPO3 10.4.12 and tried 4.3.0 of the extension. 
And also I can't see the tab comments.

Can you confirm this issue?

Best,
Andrea

**Comment by nitsan-technologies** [comment]
Dear Andrea,

It seems you are not aware, we have a premium version of this extension. If you are interested to get those missing features, You will need to grab the premium version. Take a look at https://t3terminal.com/news-comment-typo3-extension

Cheers,
Team NITSAN
