### ISSUE TITLE
Can't add comment, pro version

### ISSUE THREAD

**Issue by AstCommodore** [nitsan-technologies/ns_news_comments#41]
Hi there!

I setup the extension and license as descripted in the documentation, but I couldn't get the extension to run:

Composer installation (on DDEV and remote staging)
TYPO3 11.5.6
news 9.2.0
ns_news_comments 5.0.3

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      nsnewscomment: 99
```

The create action at

`URL/nsnewscomment?tx_nsnewscomments_newscomment%5Baction%5D=create&tx_nsnewscomments_newscomment%5Bcontroller%5D=Comment&tx_nsnewscomments_newscomment%5BStoragepid%5D=1009541%2C1009542%2C1009476%2C1009383%2C1009381%2C1010070%2C1009380&cHash=ec650e97d2f53c15b91b4e7681a7d680`

gives the HTTP status code 200, but hasn't content! Therefor the XHR response is empty and the commentError() is thrown with `Unexpected end of JSON input` 

When I edit the output of the action or even remove it, the URL get's delivered with code 200 and no PHP exception will appear ...?! Seems like I edit the wrong CommentController (/extensions/ns_news_comments).

Current plugin settings are:

```
settings {
        approveComment = 0
        termsRequired = 1
        termsTypolinkParameter = 1009390
        googlecaptchaSitekey =

        notification {
            siteadmin {
                sendMailToAdmin = 0
                sendMailToUserGroup = 0
                adminEmail = info@example.com
                adminName = Admin
                fromEmail = info@example.com
                adminMailSubject = Neuer Kommentar ist eingegenagen
                sendMailToNewsAuthor = 0
            }
        }

        mainConfiguration {
            recordStoragePage = 1009380
            customDateFormat = d.m.Y
            customTimeFormat = i:H
            disableCaptcha =
            userImage = EXT:ns_news_comments/Resources/Public/Icons/team-image.png
            commentUserSettings = anonymoususer
            FEUserLoginPageId =
        }
    }
```

**Comment by nitsan-technologies** [comment]
Hello @AstCommodore 
Greetings of the day!

Thanks for the message and detailed information. FYI, We have checked your mentioned issue in our local server. But we haven't found such an issue or we are not able to reproduce this. Also, any of our other customers has not reported such an issue. Maybe it's a kind of system-specific issue.

Is it possible for you to provide us the server access details like TYPO3 backend and FTP? If so, please send us the details at here: support@t3terminal.com

Waiting for your reply here. 

Wishing you a great day ahead.

Thanks!
Team NITSAN
