### ISSUE TITLE
Error after uninstallation

### ISSUE THREAD

**Issue by lenjka01** [nitsan-technologies/ns_news_comments#42]
I don't know what to do anymore. I have already reinstalled the news extension. As soon as you get to the detail page, this error occurs:

Oops, an error occurred!
No Content Object definition found at TypoScript object path "tt_content.list.20.nsnewscomments_newscomment"

**Comment by lenjka01** [comment]
tt_content.list.20.nsnewscomments_newscomment =
in the setup
saved it, but you should develop an extension in such a way that it can be deleted without any problems

**Comment by nitsan-technologies** [comment]
Hi @lenjka01,

Thank you for reaching out regarding our extension.

One thing to note: when you add a plugin to your page, it is stored in the tt_content table. You may have missed removing the record from there, which could be causing the issue. This is not related to our extension.

For further reference, you can check here: https://docs.typo3.org/m/typo3/reference-exceptions/main/en-us/Exceptions/1253191023.html#removed-inactive-extension.

Thanks,
Team @nitsan-technologies

**Comment by lenjka01** [comment]
Really? After 2 and a half years?

**Comment by nitsan-technologies** [comment]
Hey @lenjka01 

Sorry for the delayed response, and we apologize for any inconvenience caused.
After reviewing the issue, we found that it may not be directly related to the extension. However, we truly appreciate your patience and will strive to be more responsive moving forward.

If you still have any questions or concerns, please let us know the specifics, and we'll be happy to assist you.

Best Regards
Team @nitsan-technologies
