### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by franhida** [nitsan-technologies/ns_news_comments#45]
Hello Nitsan Team.

I have been recently investigating on how to help to translate TYPO3.
Apparently how they do it is by connecting the proyects to [Crowdin](https://crowdin.com/).

Following one of the TYPO3 translation team's member's advice, I'm reaching you out to suggest you to join said platform in order to make easier for translators to help with translating your extensions.

While you make up your mind on whether to join the platform or not, I'm leaving in PR #44 the translations for Spanish.

Regards.

**Comment by nitsan-technologies** [comment]
Hello @franhida 

Thanks for the support ! We warmly appreciate your hard work.

Thanks from the team NITSAN

**Comment by nitsan-technologies** [comment]
Hello @franhida 

Again thanks for the support. FYI, We have merged your request and released a new version with this. 

Have a great time ahead.

Thanks!
Team NITSAN

**Comment by franhida** [comment]
@nitsan-technologies, thanks for your reply and releasing the new version.

I'll keep in touch should I find any typos within the translations o I have any further suggestions for your extensions.

Have a nice day.

franhida
