### ISSUE TITLE
After submit: JSON data and timeout when loading detail page again.

### ISSUE THREAD

**Issue by fishbone1** [nitsan-technologies/ns_news_comments#47]
## Actual
* After submitting a news comment, a new page with JSON data opens.
* If a news entry has at least one enabled comment, you cannot open the news entry page anymore. It will load until a timeout occurs.

## Expected
The news entry is shown with comments below after submission (like in the free version). No timeouts to occur when loading the news detail page again.

## Versions

Version: ns_news_comments 5.4.2
TYPO3 version: 11.5.22
PHP 8.1

## Addtional notes:

~~Everything worked on another test system which has the same setup. We removed the license from the test system and attached it to the main system. But we tested a while ago so maybe we had an older version. But it even works now on the test system with the free _version.~~
I swapped the license again. The same issue occurs on the test system as soon as the premium version is installed

The page works again as soon as I disable or delete the comments.

JSON data looks like this:
```
{"5":{"parentId":"","comment":"comment"}}
```
Sometimes it contains a success note.

**Comment by fishbone1** [comment]
The timeout issue disappears if I set `disableOverrideDemand` in the news detail plugin.

The JSON issue is probably caused by JS errors that prevent your JS from being executed. Those other JS errors are caused due to multiple jQuery versions being loaded. We have our own. Solr extension provides one and your ext as well. The problem with your version is that it's pretty out dated.

To exclude your jQuery I had to include your extension typo config BEFORE my site package. This leads to another problem:
bootstrap_package wraps all content elements with a frame HTML markup. So the "create comment" AJAX response will contain your JSON wrapped by that HTML. I got rid of that by adding a condition in bootstrap_package's content elment layout. The layout will be empty if `list_type` equals `nsnewscomments_newscomment`.
But maybe there are better ways than a custom PAGE type to implement AJAX requests. (https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Backend/Ajax.html)

**Comment by nitsan-technologies** [comment]
Hey @fishbone1 

According to our last discussion (on an email thread), Your mentioned issue caused a problem with the jQuery version. Our team is worked on Option #2, Upgrading the jQuery core version.

Please update the latest version (free or premium) https://docs.t3planet.com/en/latest/License/UpdateVersion/Index.html

Go to Template > Constant Editor > You can choose the jQuery version. In your case, You should consider setting the latest jQuery 3.x

Please feel free to write us back if you need any more help.

Once again, Thank you very much for your feedback to keep improving the product.

Cheers, Team NITSAN
