### ISSUE TITLE
PHP 8.x compatibility

### ISSUE THREAD

**Issue by r3h6** [nitsan-technologies/ns_news_comments#49]
Installing v5.1.0 in TYPO3 v11 on PHP 8.1 (ddev) throws following error:
`PHP Warning: Undefined array key "tx_nsnewscomments_newscomment" in /var/www/html/web/typo3conf/ext/ns_news_comments/Classes/Controller/CommentController.php line 126`

**Comment by develth** [comment]
also the deprecated dynamic vars:

https://github.com/nitsan-technologies/ns_news_comments/blob/master/Classes/Controller/CommentController.php#L119

**Comment by nitsan-technologies** [comment]
Hey Everyone,

Thanks for your feedback. We have already fixed the PHP warning and deprecation. We are going to release the version within a week. We appreciate your patience and support.

Cheers, Team NITSAN

**Comment by develth** [comment]
thx @nitsan-technologies
do you have a exact date for us? this currently blocks the migration of a site. 
Thx

**Comment by nitsan-technologies** [comment]
Hey Everyone,

:rocket: We have released v12.0.0 compatibility of PHP 8.x. Check https://github.com/nitsan-technologies/ns_news_comments/releases/tag/12.0.0

Thank you all for your patience and support.

Cheers, Team NITSAN
