### ISSUE TITLE
Enable requiring specific version

### ISSUE THREAD

**Issue by beath** [nitsan-technologies/ns_news_comments#6]
Currently it is only possible to require dev-master of the extension via composer. For stable live systems it should also be possible to require a specific version.

As far as I know, you can to this by adding git tags to your commits. For example, the current version is 2.0.1:

`git tag 2.0.1`
`git push --tags`

**Comment by nitsan-technologies** [comment]
Hello @beath 

Thank you for your suggestions and solutions :)

We have added the tag(2.0.1) to this repository.
We will add all version tags from now for every new release.

Cheers!

**Comment by beath** [comment]
Great, works as expected.
