### ISSUE TITLE
Typoscript defintion of ajax PAGE-Object unsafe

### ISSUE THREAD

**Issue by beath** [nitsan-technologies/ns_news_comments#7]
ns_news_comments/Configuration/TypoScript/setup.txt Line 54

`10 < tt_content.list.20.nsnewscomments_newscomment`

This only works if the Typoscript is included after the plugins are registered in php which may be after your code. In that case the extension does not work. It should be:

```
ajaxCall = PAGE
ajaxCall.10 = USER
ajaxCall.10 {
    userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
    extensionName = NsNewsComments
    pluginName = Newscomment
    vendorName = Nitsan
    controller = Comment
}
```

(The naming "ajaxCall" is also not optimal, ajaxComments or even ajaxNsNewsComments would be better to avoid unwanted overwriting by other extensions).

**Comment by nitsan-technologies** [comment]
Hey @beath 

Yes, that is the batter idea.
Thanks for your suggestion.

Currently, we have adopted the code at GIT and soon we will upload it TER too.

Thanks :)
