### ISSUE TITLE
TCA overrides of tx_news_domain_model_news

### ISSUE THREAD

**Issue by beath** [nitsan-technologies/ns_news_comments#8]
ns_news_comments/Configuration/TCA/Overrides/tx_news_domain_model_news.php Lines 6 and 7

Line 7 is not needed. It would actually add a second div "comments" in the backend. Luckily divs with no fields in it are not rendered. Also the name of you div "Comments" is untranslated and untranslatable.

This is not how you should add fields and divs to a table of a third party extension. You should not directly manipulate the string of showitem (or any TCA). You should use 

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns`
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes`

and also palettes: https://docs.typo3.org/typo3cms/TCAReference/Palettes/Index.html

**Comment by nitsan-technologies** [comment]
Hey @beath 

Thanks for your review :)

Yes, we have updated the code.
You can check it at GIT version and let 
Soon we will upload it at  TER too.

Cheers!
